/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.ControllerFormulir;
import java.awt.Window;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import model.Mahasiswa;
/**
 *
 * @author Ayaa
 */
public class ViewFormulir extends javax.swing.JPanel {
     private ControllerFormulir controller;
    /**
     * Creates new form ViewFormulir
     */

    public ViewFormulir() {
        controller = new ControllerFormulir(this);
        initComponents();
    }
    
    public void showUpdateForm(Mahasiswa mahasiswa) {
        // Update text fields with Mahasiswa details
        emailTextField.setText(mahasiswa.getEmail());
        namaTextField.setText(mahasiswa.getNama());
        nimTextField.setText(mahasiswa.getNim());
        kelasTextField.setText(mahasiswa.getKelas());
        telpTextField.setText(mahasiswa.getTelp());
        if (mahasiswa.getJk().equalsIgnoreCase("Laki-laki")) {
            lakiRadioButton.setSelected(true);
        } else {
            perempuanRadioButton.setSelected(true);
        }
        tglDateChooser.setDate(java.sql.Date.valueOf(mahasiswa.getTgl()));
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        apkLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        telpTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        kelasLabel = new javax.swing.JLabel();
        kelasTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        telpLabel = new javax.swing.JLabel();
        jkLabel = new javax.swing.JLabel();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        tglDateChooser = new com.toedter.calendar.JDateChooser();
        tglLabel = new javax.swing.JLabel();
        simpanButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));

        jPanel1.setBackground(new java.awt.Color(252, 232, 181));

        apkLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        apkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apkLabel.setText("Formulir Peminjaman Gym");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setText("EMAIL");

        namaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLabel.setText("NAMA");

        nimLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nimLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nimLabel.setText("NIM");

        kelasLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kelasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kelasLabel.setText("KELAS");

        telpLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telpLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        telpLabel.setText("NO TELEPON");

        jkLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jkLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel.setText("JENIS KELAMIN");

        buttonGroup1.add(lakiRadioButton);
        lakiRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lakiRadioButton.setText("Laki-laki");

        buttonGroup1.add(perempuanRadioButton);
        perempuanRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        perempuanRadioButton.setText("Perempuan");

        tglLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tglLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tglLabel.setText("TANGGAL PENGGUNAAN RUANG GYM");

        simpanButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        simpanButton.setText("SIMPAN");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 320, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nimLabel)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telpLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(namaLabel)
                                    .addComponent(kelasLabel)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jkLabel))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kelasTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lakiRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(perempuanRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tglLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tglDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(288, 288, 288))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simpanButton)
                .addGap(445, 445, 445))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(apkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backButton)
                        .addGap(53, 53, 53)
                        .addComponent(apkLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaLabel))
                        .addGap(18, 18, 18)
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nimLabel)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelasTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelasLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telpLabel)
                    .addComponent(telpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkLabel)
                    .addComponent(lakiRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perempuanRadioButton)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglLabel))
                .addGap(59, 59, 59)
                .addComponent(simpanButton)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        try {
        controller.insert(); 
        navigateToDashboard();
    } catch (SQLException ex) {
        Logger.getLogger(ViewFormulir.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error saving data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }             
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ViewDashboard viewDashboard = new ViewDashboard();
        JFrame frame = new JFrame("Dashboard User");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(viewDashboard);
        frame.pack();
        frame.setVisible(true);
        ((Window) this.getTopLevelAncestor()).dispose(); // Close current registratio
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apkLabel;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jkLabel;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JTextField kelasTextField;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JButton simpanButton;
    private javax.swing.JLabel telpLabel;
    private javax.swing.JTextField telpTextField;
    private com.toedter.calendar.JDateChooser tglDateChooser;
    private javax.swing.JLabel tglLabel;
    // End of variables declaration//GEN-END:variables

    public JTextField getEmailTextField() {
        return telpTextField;
    }

    public JTextField getKelasTextField() {
        return kelasTextField;
    }

    public JRadioButton getLakiRadioButton() {
        return lakiRadioButton;
    }

    public JTextField getNamaTextField() {
        return namaTextField;
    }

    public JTextField getNimTextField() {
        return nimTextField;
    }

    public JRadioButton getPerempuanRadioButton() {
        return perempuanRadioButton;
    }

    public JButton getSimpanButton() {
        return simpanButton;
    }

    public JTextField getTelpTextField() {
        return emailTextField;
    }

    public JDateChooser getTglDateChooser() {
        return tglDateChooser;
    }

    public JButton getBackButton() {
        return backButton;
    }
    
    public void closeForm() {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose(); // Menutup frame ViewFormulir
    }
    
    private void navigateToDashboard() {
    // Close current form
    closeForm();
    
    // Show ViewDashboard
    JFrame frame = new JFrame("Dashboard");
    ViewDashboard viewDashboard = new ViewDashboard();
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Adjust this as per your application flow
    frame.add(viewDashboard);
    frame.pack();
    frame.setVisible(true);
}
    
}
