/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.ControllerPeminjam;
import java.awt.Window;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ayaa
 */
public class ViewPeminjam extends javax.swing.JPanel {
    ControllerPeminjam controllerPeminjam;

    /**
     * Creates new form ViewCRUD
     */
    public ViewPeminjam(){
        initComponents();
        controllerPeminjam = new ControllerPeminjam(this);
        controllerPeminjam.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();
        cariButton = new javax.swing.JButton();
        cariLabel = new javax.swing.JLabel();
        cariTextField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        apkLabel = new javax.swing.JLabel();
        tglDateChooser = new com.toedter.calendar.JDateChooser();
        emailLabel = new javax.swing.JLabel();
        telpTextField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        kelasTextField = new javax.swing.JTextField();
        nimLabel = new javax.swing.JLabel();
        kelasLabel = new javax.swing.JLabel();
        telpLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jkLabel = new javax.swing.JLabel();
        tglLabel = new javax.swing.JLabel();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(252, 232, 181));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Telepon", "Nama", "NIM", "Kelas", "Email", "Jenis Kelamin", "Tanggal Kunjungan"
            }
        ));
        mahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mahasiswaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mahasiswaTable);

        cariButton.setText("CARI");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        cariLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cariLabel.setText("Cari Data :");

        cariTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTextFieldActionPerformed(evt);
            }
        });

        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        apkLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        apkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apkLabel.setText("APLIKASI PEMINJAMAN RUANGAN GYM ");

        emailLabel.setText("EMAIL");

        namaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLabel.setText("NAMA");

        nimLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nimLabel.setText("NIM");

        kelasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kelasLabel.setText("KELAS");

        telpLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        telpLabel.setText("NO TELEPON");

        buttonGroup1.add(lakiRadioButton);
        lakiRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lakiRadioButton.setText("Laki-laki");

        buttonGroup1.add(perempuanRadioButton);
        perempuanRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        perempuanRadioButton.setText("Perempuan");

        jkLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel.setText("JENIS KELAMIN");

        tglLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tglLabel.setText("TANGGAL PENGGUNAAN RUANG GYM");

        ubahButton.setText("UBAH");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("HAPUS");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cariLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cariButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nimLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(kelasLabel)
                                                        .addGap(50, 50, 50))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(namaLabel)
                                                            .addComponent(emailLabel))
                                                        .addGap(40, 40, 40)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(110, 110, 110)
                                                        .addComponent(telpLabel))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(110, 110, 110)
                                                        .addComponent(jkLabel))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(110, 110, 110)
                                                        .addComponent(tglLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backButton)
                                        .addGap(603, 603, 603)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lakiRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(perempuanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(hapusButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ubahButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(apkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apkLabel)
                    .addComponent(backButton))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telpLabel)
                    .addComponent(telpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLabel)
                    .addComponent(lakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nimLabel)
                            .addComponent(tglDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kelasLabel)
                            .addComponent(kelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tglLabel)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariLabel)
                    .addComponent(cariButton)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubahButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hapusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mahasiswaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mahasiswaTableMouseClicked
        controllerPeminjam.isiFields(mahasiswaTable.getSelectedRow());
    }//GEN-LAST:event_mahasiswaTableMouseClicked

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        controllerPeminjam.cariNama();
    }//GEN-LAST:event_cariButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        controllerPeminjam.isiTabel();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        controllerPeminjam.delete();
        controllerPeminjam.isiTabel();
        controllerPeminjam.reset();
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        controllerPeminjam.update();
        controllerPeminjam.isiTabel();
        controllerPeminjam.reset();
    }//GEN-LAST:event_ubahButtonActionPerformed

    private void cariTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTextFieldActionPerformed
    }//GEN-LAST:event_cariTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        ViewAdmin viewAdmin = new ViewAdmin();
        JFrame frame = new JFrame("Dashboard Admin");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(viewAdmin);
        frame.pack();
        frame.setVisible(true);
        ((Window) this.getTopLevelAncestor()).dispose(); // Close current reg
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apkLabel;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cariButton;
    private javax.swing.JLabel cariLabel;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton hapusButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jkLabel;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JTextField kelasTextField;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JTable mahasiswaTable;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel telpLabel;
    private javax.swing.JTextField telpTextField;
    private com.toedter.calendar.JDateChooser tglDateChooser;
    private javax.swing.JLabel tglLabel;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables

    public JButton getCariButton() {
        return cariButton;
    }

    public JTextField getCariTextField() {
        return cariTextField;
    }

    public JTextField getEmailTextField() {
        return emailTextField;
    }

    public JButton getHapusButton() {
        return hapusButton;
    }

    public JLabel getKelasLabel() {
        return kelasLabel;
    }

    public JTextField getKelasTextField() {
        return kelasTextField;
    }

    public JRadioButton getLakiRadioButton() {
        return lakiRadioButton;
    }

    public JTable getMahasiswaTable() {
        return mahasiswaTable;
    }

    public JTextField getNamaTextField() {
        return namaTextField;
    }

    public JTextField getNimTextField() {
        return nimTextField;
    }

    public JRadioButton getPerempuanRadioButton() {
        return perempuanRadioButton;
    }

    public JButton getRefreshButton() {
        return refreshButton;
    }


    public JTextField getTelpTextField() {
        return telpTextField;
    }

    public JDateChooser getTglDateChooser() {
        return tglDateChooser;
    }

    public JButton getUbahButton() {
        return ubahButton;
    }
    
    
}
